config/routes.rb
MtAccountUsers::Engine.routes.draw do
	resources :users do
		member do
			get 'activate'
			get 'deactivate'
		end
		collection do
			get 'import/new' => 'users#import_new'
			post 'import' => 'users#import_create'
			get 'import/summary' => 'users#import_summary'
		end
	end
end

app/controllers/mt_account_users/application_controller.rb
module MtAccountUsers
  class ApplicationController < ActionController::Base
  	def current_tenant
		@tenant = Tenant.new(current_user)
	end
	helper_method :current_tenant

	def authenticate_admin!
		if user_signed_in?
			render 'shared/errors/authorization_error' unless current_user.user_type == "admin"
		end
	end
  end
end

app/controllers/mt_account_users/users_controller.rb
module MtAccountUsers
  class UsersController < ApplicationController
  	before_action :authenticate_user!
  	before_action :authenticate_admin! if MtAccountUsers.mt_account_users_admin_only_feature == true
  	layout MtAccountUsers.mt_account_users_layout_name

  	def index
  		@users = current_tenant.users
  		@users = @users.tagged_with(params[:tag], :on => :tags, :owned_by => current_tenant.account) if !params[:tag].blank?
  		respond_to do |format|
			format.html { @users = @users.decorate }
			format.csv { send_data to_csv(@users) }
		end
  	end

  	def show
  		@user = current_tenant.users.find(params[:id]).decorate
  	end

 	def new
  		@user = current_tenant.users.new
  	end

  	def edit
  		@user = current_tenant.users.find(params[:id])
  		@tags = current_tenant.tags
  	end

  	def create
		@user = current_tenant.users.new(user_params)
		if @user.save
			current_tenant.account.tag(@user, :with => params[:user][:tag_list], :on => :tags)
			redirect_to @user, notice: 'User was successfully created.' 
		else
			render action: "new"
		end
	end

	def update
		@user = current_tenant.users.find(params[:id])
		if @user.update_attributes(user_params)
			current_tenant.account.tag(@user, :with => params[:user][:tag_list], :on => :tags)
			redirect_to @user, notice: 'User was successfully updated.'
		else 
			render action: "edit" 
		end
	end

	def activate
		@user = current_tenant.users.find(params[:id])
		@user.update(active: true)

		redirect_to :back, notice: 'User was successfully activated'
	end

	def deactivate
		@user = current_tenant.users.find(params[:id])
		@user.update(active: false)

		redirect_to :back, notice: 'User was successfully deactivated'
	end

	def import_new
		render '/mt_account_users/users/import/new'
	end

	def import_create
		user_import_service =  UsersImportService.new(params[:users_csv], params[:password], params[:tag_list])
		if user_import_service.import_params_valid?
			if user_import_service.import_file_valid?
				user_import_service.create_users(current_user, request.remote_ip)
				@import_error_messages = user_import_service.import_error_messages
				@success_import_count = user_import_service.success_import_count
				@failed_import_count = user_import_service.failed_import_count
				render '/mt_account_users/users/import/summary'
			else
				@import_error_messages = user_import_service.file_error_messages
				render '/mt_account_users/users/import/new'
			end
		else
			@import_error_messages = user_import_service.params_error_messages
			render '/mt_account_users/users/import/new'
		end
	end

  	private
	def user_params
		if params[:action] == 'create'
			params[:user][:account_id]=current_user.account_id
			params[:user][:created_by]=current_user.id
			params[:user][:created_ip]=request.remote_ip
		end
		# handle "leave password blank if you do not want to change"
		if params[:action] == 'update'
			params[:user].delete :password if params[:user][:password].blank?
			params[:user].delete :password_confirmation if params[:user][:password_confirmation].blank?
		end
		params[:user][:updated_by]=current_user.id
		params[:user][:updated_ip]=request.remote_ip

		params.require(:user).permit(:email, :first_name, :last_name, :user_type, :password, :password_confirmation, :account_id, :created_by, :created_ip, :updated_by, :updated_ip)  
	end

	private
	def to_csv users
		CSV.generate do |csv|
		csv << ["Email", "First name", "Last name"]
			users.each do |user|
				csv << [user.email, user.first_name, user.last_name]
			end
		end
	end
  end
end

app/helpers/mt_account_users/application_helper.rb
module MtAccountUsers
  module ApplicationHelper
  end
end

app/helpers/mt_account_users/users_helper.rb
module MtAccountUsers
  module UsersHelper
  	def gravatar128 email
		# include MD5 gem, should be part of standard ruby install
		# require 'digest/md5'
		 
		# get the email from URL-parameters or what have you and make lowercase
		email_address = email.downcase
		 
		# create the md5 hash
		hash = Digest::MD5.hexdigest(email_address)
		 
		# compile URL which can be used in <img src="RIGHT_HERE"...
		image_src = "http://www.gravatar.com/avatar/#{hash}?s=128&d=identicon"

		image_tag(image_src, class: "img-responsive")
	end

	def avatar user
		begin
			if !user.avatar.blank?
				return image_tag(user.avatar.url, class: "img-responsive")
			else
				# include MD5 gem, should be part of standard ruby install
				# require 'digest/md5'
				 
				# get the email from URL-parameters or what have you and make lowercase
				email_address = user.email.downcase
				 
				# create the md5 hash
				hash = Digest::MD5.hexdigest(email_address)
				 
				# compile URL which can be used in <img src="RIGHT_HERE"...
				image_src = "http://www.gravatar.com/avatar/#{hash}?s=128&d=identicon"

				return image_tag(image_src, class: "img-responsive")
			end
		rescue
			# include MD5 gem, should be part of standard ruby install
			# require 'digest/md5'
			 
			# get the email from URL-parameters or what have you and make lowercase
			email_address = user.email.downcase
			 
			# create the md5 hash
			hash = Digest::MD5.hexdigest(email_address)
			 
			# compile URL which can be used in <img src="RIGHT_HERE"...
			image_src = "http://www.gravatar.com/avatar/#{hash}?s=128&d=identicon"

			return image_tag(image_src, class: "img-responsive")
		end
	end
  end
end

app/views/layouts/mt_account_users/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MtAccountUsers</title>
  <%= stylesheet_link_tag    "mt_account_users/application", media: "all" %>
  <%= javascript_include_tag "mt_account_users/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mt_account_users/users/_grid.html.erb
<% if @users.count > 0 %>
	<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th><th>Email</th><th>Type</th><th>Status</th><th>Created at</th><th>Created by</th><th></th>
			</tr>
		</thead>
		<tbody>
			<% @users.each do |user| %>
				<tr>
					<td><%= user.full_name %></td>
					<td><%= user.email %></td>
					<td><%= user.user_type.titleize unless user.user_type.blank? %></td>
					<td><%= 'Active' if user.active %>
						<%= 'Inactive' if !user.active %></td>
					<td><%= user.created_at %></td>
					<td><%= user.created_by %></td>
					<td class="text-right">
						<%= link_to "View", user %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	</div>
<% else %>
	<div data-alert class="alert alert-danger up-10">
		<p>Something is really wrong, if there are no users in this account, then who are you???</p>
	</div>
<% end %>

app/views/mt_account_users/users/_panel_form.html.erb
<%= simple_form_for @user, html: {class: "form-modern"} do |f| %>
	<div class="panel-body">
		<%= f.input :email, required: true %>
		<%= f.input :first_name, required: true %>
		<%= f.input :last_name, required: true %>
		<%= f.input :user_type, collection: MtAccountUsers.mt_account_users_user_type, include_blank: false %>
		<%= f.input :tag_list, input_html: {class: "tags-tokenfield", placeholder: "Type something and hit enter", data: {tokens: @user.tags_from(current_tenant.account)} } %>
		<%# to handle whether to display password or not %>
		<% if @user.new_record? %>
			<%= f.input :password, required: true, hint: "8 characters minimum" %>
			<div class="panel panel-default"><div class="panel-body">
			<%= f.input :password_confirmation, required: true %>
			</div></div>
		<% elsif MtAccountUsers.mt_account_users_admin_edit_password == true || @user == current_user %>
			<%= f.input :password, required: true, hint: "8 characters minimum", input_html: {placeholder: "Leave blank if you do not want to change"} %>
			<div class="panel panel-default"><div class="panel-body">
			<%= f.input :password_confirmation, required: true %>
			</div></div>
		<% end %>
	</div>
	<div class="panel-footer text-right">
		<%= f.button :submit, class: "btn btn-submit btn-sm" %>
		<%= link_to 'Cancel', users_path, class: "btn btn-cancel btn-sm" %>
	</div>
<% end %>

app/views/mt_account_users/users/edit.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li><%= link_to @user.full_name, @user %></li>
		<li class="active">Edit</li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to @user.full_name, @user %></li>
			  <li><%= link_to "Edit", edit_user_path(@user) %></li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to @user.full_name, @user %></li>
			  <li><%= link_to "Edit", edit_user_path(@user) %></li>
		  </ol>
	    </div>
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<h3 class="panel-title">Edit user</h3>
			</div>
			<%= render "panel_form" %>
		</div>
	</div>
</div>

app/views/mt_account_users/users/import/new.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li class="active"><%= link_to "Import", import_new_users_path %></li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to "Import", import_new_users_path %></li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to "Import", import_new_users_path %></li>
		  </ol>
	    </div>
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<h3 class="panel-title">CSV import file format</h3>
			</div>
			<div class="panel-body">
				<table class="table table-striped">
					<thead>
						<tr><th>email*</th><th>first_name*</th><th>last_name*</th></tr>
					</thead>
					<tbody>
						<tr><td>mhunter3@company.com</td><td>Martha</td><td>Hunter</td></tr>
						<tr><td>jwelch0@company.com</td><td>Jerry</td><td>Welch</td></tr>
						<tr><td>jfoster1@company.com</td><td>Jason</td><td>Foster</td></tr>
						<tr><td>kfowler2@company.com</td><td>Kathryn</td><td>Fowler</td></tr>
						<tr><td>jmyers4@company.com</td><td>Joshua</td><td>Myers</td></tr>
					</tbody>
				</table>

				<small>
				<ol class="padding-left-15">
					<li>* required fields</li>
					<li>First row of CSV file must be a header</li>
				</or>
				</small>
			</div>
		</div>
	</div>
	<div class="col-md-6">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<h3 class="panel-title">Import user using CSV</h3>
			</div>
			<%= form_tag(import_users_path, method: "post", multipart: true, class: "form-modern") do %>
				<div class="panel-body">
					<% if @import_error_messages %>
						<div class="alert alert-danger" role="alert">
							<ul><% @import_error_messages.each do |msg| %><li><%= msg %></li><% end %></ul>
						</div>
					<% end %>
					<div class="form-group">
						<%= label_tag(:users_csv, "CSV file") %>
						<%= file_field_tag :users_csv %>
					</div>
					<div class="form-group">
						<%= label_tag(:password, "Default password") %> 
						<%= text_field_tag(:password, nil, class: "form-control") %>
						<span class="help-block">All users in this import will be assigned with this password.</span>
					</div>
					<div class="form-group">
						<%= label_tag(:tag_list, "Default tags") %>
						<%= text_field_tag(:tag_list, nil, class: "form-control tags-tokenfield", placeholder: "Type something and hit enter") %>
					</div>
				</div>
				<div class="panel-footer text-right">
					<%= button_tag "Import", class: "btn btn-submit btn-sm", data: {disable_with: "<i class='fa fa-refresh fa-spin'></i> Processing..."} %>
					<%= link_to 'Cancel', users_path, class: "btn btn-cancel btn-sm" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/mt_account_users/users/import/summary.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li class="active">Import summary</li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
			  <li>Import summary</li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
			  <li>Import summary</li>
		  </ol>
	    </div>
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="row">
	<div class="col-md-6">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<h3 class="panel-title">Users import summary</h3>
			</div>
			<div class="panel-body">
				<h5>Number of users created: <span class="text-success"><%= @success_import_count %></span></h5>
				<% if @failed_import_count > 0 %>
					<h5>Number of errors (please look at the table below for more details): <span class="text-error"><%= @failed_import_count %></span></h5>
					<div class="table-responsive">
					<table class="table table-striped">
						<thead>
							<tr><th>Failed rows</th><th>Error details</th></tr>
						</thead>
						<tbody>
							<% @import_error_messages.each do |error| %>
								<tr><td><b><%= error[0] %></b></td>
								<td><%= error[1].join(", ") %></td></tr>
							<% end %>
						</tbody>
					</table>
					</div>
				<% end %>
				<%= link_to "Back to users list", mt_account_users.users_path, class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/mt_account_users/users/index.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li class="active">All</li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#subnavbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
	      </button>
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
		  </ol>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="subnavbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<li><%= link_to "New user", new_user_path %></li>
			<li><%= link_to "Export all", users_path(format: "csv") %></li>
			<li><%= link_to "Import", import_new_users_path %></li>
			<% if current_tenant.account.owned_tags.count > 0 %>
			<li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Filter <span class="caret"></span></a>
	          <ul class="dropdown-menu" role="menu">
	          	<li><%= link_to "All", users_path %></li>
			    <li class="divider"></li>
			    <% current_tenant.account.owned_tags.order(name: :asc).each do |tag| %>
			    	<li><%= link_to tag.name, users_path(tag: tag.name) %></li>
			    <% end %>
	          </ul>
	        </li>
	        <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="panel panel-modern">
	<div class="panel-heading">
		<div class="row">
			<div class="col-sm-7">
				<% if params[:tag] %>
					<h3 class="panel-title">Users tagged: <%=params[:tag]%></h3>				
				<% else %>
					<h3 class="panel-title">Users</h3>
				<% end %>
			</div>
			<div class="col-sm-5">
				<% if MtAccountUsers.mt_account_users_panel_action_buttons == true %>
					<div class="text-sm-right">
						<%= link_to "New user", new_user_path, class: "btn btn-new btn-default btn-sm" %>
						<%= link_to "Export all", users_path(format: "csv"), class: "btn btn-default btn-sm" %>
						<%= link_to "Import", import_new_users_path, class: "btn btn-default btn-sm" %>
						<% if current_tenant.account.owned_tags.count > 0 %>
							<div class="btn-group">
							  <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
							    Filter <span class="caret"></span>
							  </button>
							  <ul class="dropdown-menu dropdown-menu-right" role="menu">
							    <li><%= link_to "All", users_path %></li>
							    <li class="divider"></li>
							    <% current_tenant.account.owned_tags.order(name: :asc).each do |tag| %>
							    	<li><%= link_to tag.name, users_path(tag: tag.name) %></li>
							    <% end %>
							  </ul>
							</div>
						<% end %>
					</div>
				<% end %>
			</div>
		</div>
	</div>
	<div class="panel-body">
		<%= render "grid" %>
	</div>
</div>

app/views/mt_account_users/users/new.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li class="active">New</li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to "New", new_user_path %></li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to "New", new_user_path %></li>
		  </ol>
	    </div>
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<div class="row">
					<div class="col-sm-4">
						<h3 class="panel-title">New user</h3>
					</div>
					<div class="col-sm-8">
						<div class="text-right">
						</div>
					</div>
				</div>
			</div>
			<%= render "panel_form" %>
		</div>
	</div>
</div>

app/views/mt_account_users/users/show.html.erb
<% content_for :page_title do %>
	<%= link_to 'Users', users_path, class: 'navbar-brand' %>
<% end %>

<% content_for :subnav_section do %>
	<ol class="breadcrumb breadcrumb-modern">
		<li><%= link_to 'Users', users_path %></li>
		<li class="active"><%= @user.full_name %></li>
	</ol>
<% end %>

<% content_for :subnav do %>
	<nav class="navbar navbar-subnav">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#subnavbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
	      </button>
	      <ol class="breadcrumb navbar-subnav-breadcrumb left-15 visible-xs-block">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to @user.full_name, @user %></li>
		  </ol>
	      <ol class="breadcrumb navbar-subnav-breadcrumb hidden-xs">
			  <li><%= link_to "Users", users_path %></li>
			  <li><%= link_to @user.full_name, @user %></li>
		  </ol>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="subnavbar-collapse-1">
	      <ul class="nav navbar-nav navbar-right">
	      	<% if !@user.active && @user != current_user %>
	      		<li><%= link_to "Activate", activate_user_path(@user) %></li>
	      	<% end %>
	      	<% if @user.active && @user != current_user  %>
				<li><%= link_to "Deactivate", deactivate_user_path(@user) %></li>
			<% end %>
			<li><%= link_to "Edit", edit_user_path(@user) %></li>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<% end %>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-modern">
			<div class="panel-heading">
				<div class="row">
					<div class="col-sm-4">
						<h3 class="panel-title"><%= @user.full_name %></h3>
					</div>
					<div class="col-sm-8">
						<div class="text-sm-right">
							<% if MtAccountUsers.mt_account_users_panel_action_buttons == true %>
								<%# activate and deactivate only available on other users %>
								<%= link_to "Activate", activate_user_path(@user), class: "btn btn-success btn-sm" if !@user.active && @user != current_user %>
								<%= link_to "Deactivate", deactivate_user_path(@user), class: "btn btn-warning btn-sm" if @user.active && @user != current_user %>
								<%= link_to "Edit", edit_user_path(@user), class: "btn btn-edit btn-sm" %>
							<% end %>
						</div>
					</div>
				</div>
			</div>
			<div class="panel-body">
				<div class="row">
					<div class="col-md-2 bottom-10">
						<%= avatar @user %>
					</div>
					<div class="col-md-10">
						<table class="table table-striped">
							<tr>
								<td style="width:160px;"><b>Email</b></td>
								<td><%= @user.email %></td>
							</tr>
							<tr>
								<td><b>First name</b></td>
								<td><%= @user.first_name %></td>
							</tr>
							<tr>
								<td><b>Last name</b></td>
								<td><%= @user.last_name %></td>
							</tr>
							<tr>
								<td><b>Last log in at</b></td>
								<td><%= @user.last_sign_in_at %></td>
							</tr>
							<tr>
								<td><b>Tags</b></td>
								<td><%= @user.tag_list %></td>
							</tr>
							<% MtAccountUsers.mt_account_users_extra_show_details.each do |item| %>
							<tr>
								<td><b><%= item["label"] %></b></td>
								<td><%= @user.send(item["attribute"]) %></td>
							</tr>	
							<% end %>
							<tr>
								<td><b>Created at</b></td>
								<td><%= @user.created_at %></td>
							</tr>
							<tr>
								<td><b>Created by</b></td>
								<td><%= @user.created_by %></td>
							</tr>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>